src/Entity/Agent.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AgentRepository")
 * @UniqueEntity("email")
 */
class Agent
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     * @Assert\NotBlank
     * @Assert\Email(
     *     message = "The email '{{ value }}' is not a valid email."
     * )
     */
    private $email;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Campaign", mappedBy="agent")
     */
    private $campaigns;

    public function __construct()
    {
        $this->campaigns = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(?string $firstName): self
    {
        $this->firstName = mb_convert_case($firstName, MB_CASE_TITLE, "UTF-8");

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(?string $lastName): self
    {
        $this->lastName = mb_convert_case($lastName, MB_CASE_TITLE, "UTF-8");

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = strtolower($email);

        return $this;
    }

    public function getFullName(): string
    {
        return sprintf('%s %s', $this->getFirstName(), $this->getLastName());
    }

    public function getCampaigns(): Collection
    {
        return $this->campaigns;
    }
}

src/Entity/Campaign.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use App\Validator\Constraints as AppAssert;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CampaignRepository")
 * @AppAssert\ValidPostQuantityClass()
 */
class Campaign
{
    /**
    * @ORM\Id()
    * @ORM\GeneratedValue()
    * @ORM\Column(type="integer")
    */
    private $id;

    /**
    * @ORM\Column(type="string", length=255)
    * @Assert\Regex(
    *     pattern="/[^\w #]+/",
    *     match=false,
    *     message="Your name cannot contain special characters"
    * )
    * @Assert\NotBlank
    */
    private $name;

    /**
    * @ORM\Column(type="datetime")
    * @Assert\NotBlank
    * @Assert\GreaterThan("-1 year")
    * @Assert\Type("\DateTime")
    */
    private $startDate;

    /**
    * @ORM\Column(type="datetime")
    * @Assert\NotBlank
    * @Assert\GreaterThan(propertyPath="startDate")
    * @Assert\Type("\DateTime")
    */
    private $endDate;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Assert\NotBlank
     * @Assert\Type(type="integer")
     * @Assert\Range(min=1, minMessage="A campaign should have at least one post.")
     */
    private $postsQuantity;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $pid;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $notice;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $token;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $expiresAt;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Agent", inversedBy="campaigns")
     */
    private $agent;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Post", mappedBy="campaign", cascade={"persist"})
     * @Assert\Valid()
     */
    private $posts;

    public function __construct()
    {
        $this->posts = new ArrayCollection();
        $this->postsQuantity = 1;
    }

    public function getId(): int
    {
        return $this->id;
    }

    public function setName(?string $name): void
    {
        $this->name = $name;
    }

    public function setStartDate(?\DateTimeInterface $startDate): void
    {
        $this->startDate = $startDate;
    }

    public function setEndDate(?\DateTimeInterface $endDate): void
    {
        $this->endDate = $endDate;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function getStartDate(): ?\DateTime
    {
        return $this->startDate;
    }

    public function getEndDate(): ?\DateTime
    {
        return $this->endDate;
    }

    public function getPostsQuantity(): ?int
    {
        return $this->postsQuantity;
    }

    public function setPostsQuantity(?int $postsQuantity): void
    {
        $this->postsQuantity = $postsQuantity;
    }

    public function getPid(): ?string
    {
        return $this->pid;
    }

    public function setPid(?string $pid): void
    {
        $this->pid = $pid;
    }

    public function getNotice(): ?string
    {
        return $this->notice;
    }

    public function setNotice(?string $notice): self
    {
        $this->notice = $notice;

        return $this;
    }

    public function getToken(): ?string
    {
        return $this->token;
    }

    public function setToken(?string $token): self
    {
        $this->token = $token;

        return $this;
    }

    public function getExpiresAt(): ?\DateTimeInterface
    {
        return $this->expiresAt;
    }

    public function setExpiresAt(?\DateTimeInterface $expiresAt): self
    {
        $this->expiresAt = $expiresAt;

        return $this;
    }

    public function getAgent(): ?Agent
    {
        return $this->agent;
    }

    public function setAgent(?Agent $agent): self
    {
        $this->agent = $agent;

        return $this;
    }

    public function getPosts(): Collection
    {
        return $this->posts;
    }

    public function addPost(Post $post): void
    {
        $this->posts->add($post);
        $post->setCampaign($this);
    }

    public function removePost(Post $post): void
    {
        $this->posts->removeElement($post);
    }

    public function isExpired(): bool
    {
        if (new \DateTime('now') >= $this->getExpiresAt()) {
            return true;
        }

        return false;
    }
}

src/Controller/CampaignController.php
<?php

namespace App\Controller;

use App\Entity\Agent;
use App\Form\CreateCampaignType;
use App\Entity\Campaign;
use App\Form\LoginAgentType;
use App\Form\ManageCampaignPostsType;
use App\Form\ManageCampaignType;
use App\Notification\Enum\NotificationType;
use App\Repository\AgentRepository;
use App\Repository\CampaignRepository;
use App\Service\IdGeneratorInterface;
use App\Service\TokenGenerator;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class CampaignController extends AbstractController
{
    private const TOKEN_EXPIRE = '2 hours';

    /**
     * @Route("/admin/campaign/show", name="campaign_show")
     */
    public function show(CampaignRepository $campaignRepository): Response
    {
        $campaigns = $campaignRepository->findAll();

        return $this->render(
            'Campaign/showCampaign.html.twig',
            [
                'campaigns' => $campaigns
            ]
        );
    }

    /**
    * @Route("/admin/campaign/create", name="campaign_create")
    */
    public function create(
        Request $request,
        EntityManagerInterface $entityManager,
        IdGeneratorInterface $idGenerator
    ): Response {
        $form = $this->createForm(CreateCampaignType::class);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $campaign = $form->getData();
            $campaign->setPid($idGenerator->getId());

            $entityManager->persist($campaign);
            $entityManager->flush();

            $this->addFlash(
                NotificationType::SUCCESS()->getValue(),
                sprintf('Campaign <i>%s</i> created!', $campaign->getName())
            );

            return $this->redirectToRoute('campaign_create');
        }

        return $this->render(
            'Campaign/createCampaign.html.twig',
            [
                'createCampaignForm' => $form->createView(),
            ]
        );
    }

    /**
     * @Route("/admin/campaign/manage/{id}", name="campaign_manage", requirements={"id"="\d+"})
     */
    public function manage(
        Request $request,
        EntityManagerInterface $entityManager,
        Campaign $campaign
    ): Response {
        $form = $this->createForm(ManageCampaignType::class, $campaign);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $campaign = $form->getData();

            $entityManager->flush();

            $this->addFlash(
                NotificationType::SUCCESS()->getValue(),
                sprintf('Campaign <i>%s</i> updated.', $campaign->getName())
            );

            return $this->redirectToRoute('campaign_show');
        }

        return $this->render(
            'Campaign/manageCampaign.html.twig',
            [
                'campaign' => $campaign,
                'manageCampaignForm' => $form->createView()
            ]
        );
    }

    /**
     * @Route("/campaign/getaccess/{pid}", name="campaign_getaccess")
     */
    public function getaccess(
        Request $request,
        EntityManagerInterface $entityManager,
        AgentRepository $agentRepository,
        Campaign $campaign,
        \Swift_Mailer $mailer,
        string $pid
    ): Response {
        $accessForm = $this->createForm(LoginAgentType::class);
        $accessForm->handleRequest($request);

        if ($accessForm->isSubmitted() && $accessForm->isValid()) {
            $data = $accessForm->getData();

            $agent = $agentRepository->findAssignedAgentEmailByCampaignPid($pid);

            if ($agent instanceof Agent && $data->email === $agent->getEmail()) {
                $tokenGenerator = new TokenGenerator();

                $campaign->setToken($tokenGenerator->getToken());
                $campaign->setExpiresAt(new \DateTime(self::TOKEN_EXPIRE));

                $entityManager->persist($campaign);
                $entityManager->flush();

                $this->addFlash(
                    NotificationType::SUCCESS()->getValue(),
                    'Access token has been generated. Check Your e-mail for further instructions.'
                );

                $mailer->send($this->createEmail($agent, $campaign));

                return $this->redirectToRoute('campaign_getaccess', ['pid' => $pid]);
            }

            $this->addFlash(
                NotificationType::WARNING()->getValue(),
                'Invalid email provided'
            );

            return $this->redirectToRoute('campaign_getaccess', ['pid' => $pid]);
        }

        return $this->render(
            'Security/loginCampaign.html.twig',
            [
                'accessForm' => $accessForm->createView()
            ]
        );
    }

    /**
     * @Route("/campaign/view/{token}", name="campaign_view")
     */
    public function view(
        Request $request,
        EntityManagerInterface $entityManager,
        Campaign $campaign,
        string $token
    ): Response {
        if ($campaign->isExpired()) {
            throw $this->createNotFoundException('You have no access.');
        }

        $form = $this->createForm(ManageCampaignPostsType::class, $campaign);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $campaign = $form->getData();

            $entityManager->flush();

            $this->addFlash(
                NotificationType::SUCCESS()->getValue(),
                'Post modified.'
            );

            return $this->redirectToRoute('campaign_view', ['token' => $token]);
        }
        return $this->render(
            'Campaign/viewCampaign.html.twig',
            [
                'campaign' => $campaign,
                'manageCampaignPostsForm' => $form->createView()
            ]
        );
    }

    private function createEmail(Agent $agent, Campaign $campaign): \Swift_Message
    {
         return (new \Swift_Message('BuzzApp Campaign Access'))
            ->setFrom('send@example.com')
            ->setTo($agent->getEmail())
            ->setBody(
                $this->renderView(
                    'Email/sendToken.html.twig',
                    [
                        'token' => $campaign->getToken(),
                        'firstName' => $agent->getFirstName(),
                        'campaignName' => $campaign->getName()
                    ]
                ),
                'text/html'
            );
    }
}

templates/Campaign/createCampaign.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="row mt-4 mb-2">
        <div class="col">
            <h2>Create new campaign</h2>
        </div>
    </div>

    {{ form_start(createCampaignForm, {'attr': {'novalidate': 'novalidate'}}) }}
    {{ form_widget(createCampaignForm) }}
    {{ form_end(createCampaignForm) }}
{% endblock %}

templates/Campaign/manageCampaign.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="row mt-4 mb-2">
        <div class="col">
            <h2>Manage campaign: {{ campaign.name }}</h2>
        </div>
    </div>
    <div class="row mt-2 mb-2">
        <div class="col">
            {{ form_start(manageCampaignForm, {'attr': {'novalidate': 'novalidate'}}) }}
            {{ form_row(manageCampaignForm.name) }}
            {{ form_row(manageCampaignForm.startDate) }}
            {{ form_row(manageCampaignForm.endDate) }}
            {{ form_row(manageCampaignForm.postsQuantity) }}
            {{ form_row(manageCampaignForm.agent) }}
            {{ form_row(manageCampaignForm.notice) }}
            <div class="btn-group" role="group" aria-label="Basic example">
                {{ form_widget(manageCampaignForm.save) }}
                <a href="{{ path('campaign_show') }}" class="btn btn-light">Cancel</a>
            </div>

            {{ form_end(manageCampaignForm) }}
        </div>
    </div>
    {% if campaign.posts is not empty %}

    <div class="row mt-2 mb-2">
        <div class="col">
            <h2>Written posts</h2>
        </div>
    </div>

    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Date</th>
            <th scope="col">URL</th>
            <th scope="col">Nick</th>
            <th scope="col">Category</th>
        </tr>
        </thead>
        <tbody>
        {% for post in campaign.posts %}

        <tr>
            <th scope="row">{{ post.id }}</th>
            <td>{{ post.enterDate.format('Y-m-d') }}</td>
            <td>{{ post.link }}</td>
            <td>{{ post.nick }}</td>
            <td>{{ post.category }}</td>
        </tr>

        {% endfor %}
        </tbody>
    </table>

    {% else %}

    <div class="row mt-2 mb-2">
        <div class="col">
            <h2>No posts available yet</h2>
        </div>
    </div>

    {% endif %}
{% endblock %}

templates/Campaign/showCampaign.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="row mt-4 mb-2">
        <div class="col">
            <h1>Campaign List</h1>
        </div>
        <div class="col">
            <a href="{{ path('campaign_create') }}" class="btn btn-secondary float-right">Create new campaign</a>
        </div>
    </div>

    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Name</th>
            <th scope="col">Start</th>
            <th scope="col">End</th>
            <th scope="col" colspan="2"></th>
        </tr>
        </thead>
        <tbody>
        {% for campaign in campaigns %}

        <tr>
            <th scope="row">{{ campaign.id }}</th>
            <td>{{ campaign.name }}</td>
            <td>{{ campaign.startDate.format('Y-m-d') }}</td>
            <td>{{ campaign.endDate.format('Y-m-d') }}</td>
            <td>
                {% if campaign.agent is not null %}
                    {{ campaign.agent.fullname }}
                {% else %}
                    Not assigned yet
                {% endif %}
            </td>
            <td><a href="{{ path('campaign_manage', {id: campaign.id}) }}">Manage</a></td>
            <td>
                {% if campaign.agent is not null %}
                    <a href="{{ path('campaign_getaccess', {pid: campaign.pid}) }}">View</a>
                {% endif %}
            </td>
        </tr>

        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/Campaign/viewCampaign.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="row mt-4 mb-2">
        <div class="col">
            <table class="table table-bordered">
                <tbody>
                <tr>
                    <th scope="row">Campaign</th>
                    <td colspan="3">{{ campaign.name }}</td>
                </tr>
                <tr>
                    <th scope="row">Start Date</th>
                    <td>{{ campaign.startDate.format('Y-m-d')}}</td>
                    <th scope="row">Agent</th>
                    <td>{{ campaign.agent.fullName }}</td>
                </tr>
                <tr>
                    <th scope="row">End date:</th>
                    <td>{{ campaign.endDate.format('Y-m-d') }}</td>
                    <th scope="row">Post limit</th>
                    <td><span id="postQuantity">{{ campaign.postsQuantity }}</span></td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>

    <div class="row mt-2 mb-2">
        <div class="col">
            <h2>Related posts</h2>
        </div>
    </div>

    {{ form_start(manageCampaignPostsForm, {'attr': {'novalidate': 'novalidate'}}) }}

    {{ form_errors(manageCampaignPostsForm.posts) }}

    <ul class="posts list-unstyled"
        data-prototype="{{ form_widget(manageCampaignPostsForm.posts.vars.prototype)|e('html_attr') }}"
        data-widget-tags="{{ '<li></li>'|e }}"
        data-widget-counter="{{ manageCampaignPostsForm.posts.vars.prototype|length }}">

        {% for post in manageCampaignPostsForm.posts %}
            <li>
                {{ form_widget(post) }}
            </li>
        {% endfor %}

    </ul>

    {{ form_end(manageCampaignPostsForm) }}

{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('assets/js/form/addPostsToCampaignForm.js') }}"></script>
{% endblock %}